#!/bin/bash
# ISS(detector) + SHOT352(descriptor) + LG training on new dataset.
# Requires C++ SHOT bins already generated by the external tool.

GPU_ID=${1:-0}
EXPERIMENT=${2:-"0413_new_iss_shot_lg"}
BIN_DIR=${3:-"gluefactory/datasets/new_dataset_shot_bins"}
BATCH_SIZE=${4:-32}
GT_RADIUS=${5:-20}
RESTORE=${6:-""}
CONF="gluefactory/configs/0413_new_iss_shot_lg.yaml"

RESTORE_FLAG=""
if [ "$RESTORE" = "--restore" ]; then
    RESTORE_FLAG="--restore"
    echo "=== RESUME training from last checkpoint ==="
fi

CACHE_DIR="gluefactory/datasets/new_dataset_cache/cache_new_iss_shot352"
if [ ! -d "$CACHE_DIR" ] || [ -z "$(ls -A $CACHE_DIR/*.npz 2>/dev/null)" ]; then
    echo "=== SHOT cache not found. Precomputing from bins in $BIN_DIR ... ==="
    python3 precompute_new_iss_shot.py --bin_dir "$BIN_DIR"
fi

mkdir -p "outputs/training/${EXPERIMENT}"

echo "=== Training new_dataset ISS+SHOT+LG (batch=${BATCH_SIZE}, gt_radius=${GT_RADIUS}) ==="
CUDA_VISIBLE_DEVICES=$GPU_ID python3 -m gluefactory.train_new_iss_desc "$EXPERIMENT" \
    --conf "$CONF" \
    $RESTORE_FLAG \
    --mixed_precision float16 \
    data.batch_size="$BATCH_SIZE" \
    model.ground_truth.gt_radius="$GT_RADIUS" \
    2>&1 | tee "outputs/training/${EXPERIMENT}/train.log"
