data:
    name: mitsubishi_v1_20260415_iss_shot
    descriptor_kind: shot
    data_root: /mnt/aict_nas/snuailab_datasets/Feature_Matching/dataset_output
    cache_dir: /home/jhs/work/Registration/glue-factory_depth/gluefactory/datasets/mitsubishi/iss_shot_v1_20260415_cache_vox1_nr20_sr40
    split_json: /home/jhs/work/Registration/glue-factory_depth/gluefactory/datasets/mitsubishi/splits/v1_20260415_split.json
    batch_size: 4
    num_workers: 12
model:
    name: two_view_pipeline
    filter_zero_depth: true
    extractor:
        name: extractors.superpoint_fpfh_cached
        descriptor_dim: 352
        trainable: False
    ground_truth:
        name: matchers.gt_pair_matcher
        gt_radius: 20
    matcher:
        name: matchers.lightglue
        input_dim: 352
        descriptor_dim: 352
        num_heads: 4
        filter_threshold: 0.1
        flash: false
        checkpointed: true
train:
    seed: 0
    epochs: 100
    best_key: match_recall
    best_key_mode: max
    log_every_iter: 1
    eval_every_iter: 500
    lr: 1e-4
    lr_schedule:
        start: 20
        type: exp
        on_epoch: true
        exp_div_10: 10
    plot: [5, 'gluefactory.visualization.visualize_batch.make_match_figures_depth']
